export const chatsActionTypes = {
  GET_CHAT: "GET_CHAT",
  GET_CHAT_MESSAGES: "GET_CHAT_MESSAGES",
  JOIN_CHAT: "JOIN_CHAT",
  LEAVE_CHAT: "LEAVE_CHAT",
  CREATE_MESSAGE: "CREATE_MESSAGE",
  SET_IS_LOADING_CHATS: "SET_IS_LOADING_CHATS",
  SET_FAILED_REQ_CHATS: "SET_FAILED_REQ_CHATS",
};
export enum chatsActionEnum {
  GET_CHAT = "GET_CHAT",
  GET_CHAT_MESSAGES = "GET_CHAT_MESSAGES",
  JOIN_CHAT = "JOIN_CHAT",
  LEAVE_CHAT = "LEAVE_CHAT",
  CREATE_MESSAGE = "CREATE_MESSAGE",
  SET_IS_LOADING_CHATS = "SET_IS_LOADING_CHATS",
  SET_FAILED_REQ_CHATS = "SET_FAILED_REQ_CHATS",
}
