export const eventActionTypes = {
  GET_EVENTS: "GET_EVENTS",
  GET_DETAILS: "GET_DETAILS",
  CREATE_EVENT: "CREATE_EVENT",
  ATTEND: "ATTEND",
  UNATTEND: "UNATTEND",
  EDIT_EVENT: "EDIT_EVENT",
  DELETE_EVENT: "DELETE_EVENT",
  CREATE_REVIEW: "CREATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",
  SET_IS_LOADING_EVENTS: "SET_IS_LOADING_EVENTS",
  SET_FAILED_REQ_EVENTS: "SET_FAILED_REQ_EVENTS",
};

export enum eventActionEnum {
  GET_EVENTS = "GET_EVENTS",
  GET_DETAILS = "GET_DETAILS",
  CREATE_EVENT = "CREATE_EVENT",
  ATTEND = "ATTEND",
  UNATTEND = "UNATTEND",
  EDIT_EVENT = "EDIT_EVENT",
  DELETE_EVENT = "DELETE_EVENT",
  CREATE_REVIEW = "CREATE_REVIEW",
  DELETE_REVIEW = "DELETE_REVIEW",
  SET_IS_LOADING_EVENTS = "SET_IS_LOADING_EVENTS",
  SET_FAILED_REQ_EVENTS = "SET_FAILED_REQ_EVENTS",
}
