export const noteActionTypes = {
  CREATE_NOTE: "CREATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  LIKE: "LIKE",
  UNLIKE: "UNLIKE",
  SET_IS_LOADING_NOTES: "SET_IS_LOADING_NOTES",
  SET_FAILED_REQ_NOTES: "SET_FAILED_REQ_NOTES",
};

export enum noteActionEnum {
  CREATE_NOTE = "CREATE_NOTE",
  DELETE_NOTE = "DELETE_NOTE",
  LIKE = "LIKE",
  UNLIKE = "UNLIKE",
  SET_IS_LOADING_NOTES = "SET_IS_LOADING_NOTES",
  SET_FAILED_REQ_NOTES = "SET_FAILED_REQ_NOTES",
}
