export const postActionTypes = {
  GET_FOLLOWED_POSTS: "GET_FOLLOWED_POSTS",
  SET_IS_LOADING_POSTS: "SET_IS_LOADING_POSTS",
  SET_FAILED_REQ_POSTS: "SET_FAILED_REQ_POSTS",
};

export enum postActionEnums {
  GET_FOLLOWED_POSTS = "GET_FOLLOWED_POSTS",
  SET_IS_LOADING_POSTS = "SET_IS_LOADING_POSTS",
  SET_FAILED_REQ_POSTS = "SET_FAILED_REQ_POSTS",
}
