export const uiActionTypes = {
  SHOW_OVERLAY: "SHOW_OVERLAY",
  SHOW_MOBILE_MENU: " SHOW_MOBILE_MENU",
  SHOW_AUTH_FORM: "SHOW_AUTH_FORM",
  SHOW_CATEGORIES: "SHOW_CATEGORIES",
  SET_ACCOUNT_LIST_INDEX: "SET_ACCOUNT_LIST_INDEX",
  SHOW_FOLLOWERS: "SHOW_FOLLOWERS",
  SET_FLASH: "SET_FLASH",
  SET_SHARED_EVENT: "SET_SHARED_EVENT",
  REMOVE_FLASH: "REMOVE_FLASH",
};

export enum uiActionsEnum {
  SHOW_OVERLAY = "SHOW_OVERLAY",
  SHOW_MOBILE_MENU = " SHOW_MOBILE_MENU",
  SHOW_AUTH_FORM = " SHOW_AUTH_FORM",
  SHOW_CATEGORIES = "SHOW_CATEGORIES",
  SET_ACCOUNT_LIST_INDEX = "SET_ACCOUNT_LIST_INDEX",
  SHOW_FOLLOWERS = "SHOW_FOLLOWERS",
  SET_FLASH = "SET_FLASH",
  SET_SHARED_EVENT = "SET_SHARED_EVENT",
  REMOVE_FLASH = "REMOVE_FLASH",
}
