export const interestTypes = {
  art: "art",
  cooking: "cooking",
  diy: "diy",
  education: "education",
  fitness: "fitness",
  hiking: "hiking",
  history: "history",
  it: "it",
  literature: "literature",
  music: "music",
  politics: "politics",
  science: "science",
  sightseeing: "sightseeing",
  sports: "sports",
  technologies: "technologies",
  travelling: "travelling",
  yoga: "yoga",
};

export enum InterestEnum {
  art = "art",
  cooking = "cooking",
  diy = "diy",
  education = "education",
  fitness = "fitness",
  hiking = "hiking",
  history = "history",
  it = "it",
  literature = "literature",
  music = "music",
  politics = "politics",
  science = "science",
  sightseeing = "sightseeing",
  sports = "sports",
  technologies = "technologies",
  travelling = "travelling",
  yoga = "yoga",
}
